### ISSUE TITLE
캐시 버전 사용

### ISSUE THREAD

**Issue by cheonjeongdae** [Gaia3D/ndtp#46]
javascript, image, css 에
contentCacheVersion 을 활성화

**Comment by cheonjeongdae** [comment]
interceptor 로~ ㅋ.ㅋ

**Comment by ssshpark** [comment]
interceptor로 변경하고 올린겁니다!

**Comment by cheonjeongdae** [comment]
ServletConfig.java에 Interceptor Exception url pattern 확인 할것.
거기까지 문제 없음 close

**Comment by ssshpark** [comment]
exception uri  패턴에 로그인이랑  guide 추가 되어 있어서 그부분은 컨트롤러에서 cacheVersion 추가 했는데 거기는 메뉴가 필요없는데 exception uri 패턴에서 로그인이랑 guide를 빼는게 나을까요?

**Comment by cheonjeongdae** [comment]
빼는게 상식적으로는 맞는데....
지금은 잠시 보류하고, 감리 끝나고, 시간 될때 리팩토링을 한번 합시다.

**Comment by ssshpark** [comment]
알겠습니다.
