### ISSUE TITLE
대시보드 크로스 브라우징 및 UI 개선 작업

### ISSUE THREAD

**Issue by cheonjeongdae** [Gaia3D/ndtp#75]
관리자 대시보드
 - firefox 로 사인인 후 시스템 용량 그래프 표시 안됨
 - 위젯내 폰트 사이즈가 동일하지 않음
 - 시민 참여 목록 레이블 필요.
   날짜 포맷 수정

**Comment by kimhjj** [comment]
시민참여 목록의 날짜 포맷은 어떻게 변경을 할까요? 지금은 yyyy.mm.dd. 형식입니다.
